# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c29e05d424d19c1a340491eca80f66b924e98f146d1afe97f2698008d6c97d8a5f0f87ebeb8e7be50901793220a212e7d88f2224d08d36d27edbf1b9bd69c5ee

test:
  secret_key_base: eb934c496e67f77711016e07d968041f9c85bb561aa4a85cbec0e2175c9bfe0ab5cb8e93ab7c17cb0965266eee31a5b061a60b844af67e5f598bfc44508396d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
